In [2]:
from transformers import AutoImageProcessor, Dinov2ForImageClassification

In [3]:
import torch

In [4]:
from PIL import Image

In [7]:
import matplotlib.pyplot as plt


In [9]:
# Load the pre-trained model and image processor
processor = AutoImageProcessor.from_pretrained("facebook/dinov2-base")
model = Dinov2ForImageClassification.from_pretrained("facebook/dinov2-base")

# Set the model to evaluation mode
model.eval()

Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.


{"timestamp":"2025-07-21T11:33:43.131212Z","level":"WARN","fields":{"message":"Reqwest(reqwest::Error { kind: Request, source: hyper_util::client::legacy::Error(SendRequest, hyper::Error(IncompleteMessage)) }). Retrying..."},"filename":"/Users/runner/work/xet-core/xet-core/cas_client/src/http_client.rs","line_number":242}
{"timestamp":"2025-07-21T11:33:43.131367Z","level":"WARN","fields":{"message":"Retry attempt #0. Sleeping 433.335537ms before the next attempt"},"filename":"/Users/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/reqwest-retry-0.7.0/src/middleware.rs","line_number":171}
{"timestamp":"2025-07-21T11:33:43.131449Z","level":"WARN","fields":{"message":"Reqwest(reqwest::Error { kind: Request, source: hyper_util::client::legacy::Error(SendRequest, hyper::Error(IncompleteMessage)) }). Retrying..."},"filename":"/Users/runner/work/xet-core/xet-core/cas_client/src/http_client.rs","line_number":242}
{"timestamp":"2025-07-21T11:33:43.131460Z","level":"WARN","fields":{"m

Cancellation requested; stopping current tasks.


KeyboardInterrupt: 

In [10]:
import numpy as np

In [11]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [15]:
arr[...,-1]

array([[2, 4],
       [6, 8]])

In [16]:
pad = 25

In [17]:
pad //2

12

In [18]:
pad/2

12.5

In [22]:
import torch
from torch import nn
import torch.nn.functional as F

import torch
import pandas as pd
from torch import nn
from torch import optim
from torch.utils.data import DataLoader, Dataset
from torchvision import transforms
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import numpy as np
import random
import timeit
from tqdm import tqdm

import torchvision.transforms as transforms
from torchvision.datasets import EMNIST
from torch.utils.data import DataLoader, random_split, Subset

import torchvision
from torchinfo import summary

import torchvision
from torch import optim, nn
import timeit

In [23]:
t = torch.tensor([[[1, 2],
...                    [3, 4]],
...                   [[5, 6],
...                    [7, 8]]])

In [24]:
torch.flatten(t)

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
t.shape

torch.Size([2, 2, 2])

In [27]:
torch.flatten(t,2)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [28]:
t

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])