In [2]:
from keras.models import Sequential

In [3]:
from keras.layers import Dense
import random
import numpy as np
from sklearn.preprocessing import MinMaxScaler

## Class for a simple neural network

In [61]:
# Simple Neural Network Model class
class nnModel:
    def __init__(self, input_dim, output_dim):
        self.input_dim = input_dim
        self.output_dim = output_dim
        self.model = None

    def createNN(self):
        self.model = Sequential()
        self.model.add(Dense(3, activation='relu',use_bias=True))
        self.model.add(Dense(3, activation='relu',use_bias=True))
        self.model.add(Dense(self.output_dim,activation='linear',use_bias=False))
        return self.model

    def initializeNN(self):
        self.model = self.createNN()
        self.model.compile(loss='mse', optimizer='adam', metrics=['mse','mae'])
        return self.model

    def trainNN(self, X_train, y_train, batch_size, epochs):
        self.model = self.initializeNN()
        self.model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs)
        return self.model

    def evaluateNN(self, X_test, y_test):
        self.model = self.initializeNN()
        loss, mse, mae = self.model.evaluate(X_test, y_test)
        return loss, mse, mae

## Training Data Synthesis

In [7]:
X_train_list = []
y_train_list = []
for i in range(500):
    hinge1 = random.randint(1,10)
    hinge2 = random.randint(50,100)
    y_tmp = 2*hinge1 + 0.05*hinge2 + 0.001*hinge1*hinge2
    x3 = random.randint(11,15)
    X_train_list.append([hinge1,hinge2,x3])
    y_train_list.append(y_tmp)
X_train = np.array(X_train_list)
y_train = np.array(y_train_list)

In [68]:
y_train

array([[11.402],
       [ 7.38 ],
       [ 6.284],
       [ 6.08 ],
       [22.602],
       [17.152],
       [18.845],
       [19.306],
       [ 7.276],
       [16.85 ],
       [22.366],
       [ 7.049],
       [21.953],
       [ 7.328],
       [ 4.55 ],
       [16.536],
       [11.618],
       [13.025],
       [24.2  ],
       [ 7.9  ],
       [23.782],
       [15.304],
       [11.24 ],
       [ 5.264],
       [18.503],
       [22.012],
       [19.828],
       [20.698],
       [25.88 ],
       [23.369],
       [11.51 ],
       [14.455],
       [20.466],
       [ 8.756],
       [12.806],
       [22.484],
       [ 5.468],
       [25.52 ],
       [ 9.71 ],
       [18.674],
       [ 8.732],
       [15.416],
       [18.845],
       [ 5.264],
       [17.477],
       [10.452],
       [23.78 ],
       [ 9.233],
       [ 4.55 ],
       [23.06 ],
       [13.85 ],
       [22.602],
       [ 7.952],
       [17.192],
       [15.136],
       [25.46 ],
       [17.432],
       [12.698],
       [11.996

### Normalising features and Y values

In [10]:
from sklearn.preprocessing import MinMaxScaler

In [13]:
X_train_scaled = MinMaxScaler().fit_transform(X_train_list)

In [24]:
#not needed
y_train_scaled = MinMaxScaler().fit_transform(np.array(y_train_list).reshape(-1,1))

In [30]:
y_train = np.array(y_train_list).reshape(-1,1)

## Test Data Synthesis with Normalisation of features

In [69]:
X_test_list = []
y_test_list = []
for i in range(15):
        hinge1 = random.randint(1,10)
        hinge2 = random.randint(50,100)
        y_tmp = 2*hinge1 + 0.05*hinge2 + 0.001*hinge1*hinge2
        x3 = random.randint(11,25)
        X_test_list.append([hinge1,hinge2,x3])
        y_test_list.append(y_tmp)
X_test_scaled = MinMaxScaler().fit_transform(X_test_list)

In [70]:
y_test = np.array(y_test_list).reshape(-1,1)

## Model Training 

In [62]:
model = nnModel(3,1)
model.createNN()
model.initializeNN()

<Sequential name=sequential_9, built=False>

In [37]:
model.model

<Sequential name=sequential_2, built=True>

In [63]:
model.model.summary()

Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_27 (Dense)                │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_28 (Dense)                │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_29 (Dense)                │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [71]:
y_test

array([[ 7.276],
       [17.648],
       [22.248],
       [13.076],
       [ 9.922],
       [21.304],
       [ 7.796],
       [ 8.992],
       [25.58 ],
       [11.78 ],
       [14.51 ],
       [19.358],
       [20.408],
       [ 6.998],
       [16.928]])

In [84]:
model.trainNN(X_train= X_train_scaled, y_train=y_train, batch_size=50,epochs = 700)

Epoch 1/700
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 262.6182 - mae: 14.8644 - mse: 262.6182  
Epoch 2/700
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 277.1455 - mae: 15.3367 - mse: 277.1455
Epoch 3/700
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 275.0282 - mae: 15.2960 - mse: 275.0282
Epoch 4/700
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 276.7334 - mae: 15.2801 - mse: 276.7334
Epoch 5/700
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 270.8261 - mae: 15.1299 - mse: 270.8261
Epoch 6/700
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 263.6931 - mae: 14.9842 - mse: 263.6931
Epoch 7/700
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 266.1434 - mae: 14.9872 - mse: 266.1434
Epoch 8/700
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 260.7838 - mae: 14.8114 - mse: 260.7838
Epoch 9/700
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 265.7811 - mae: 15.0135 - mse: 265.7811
Epoch 10/700
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 268.6393 - mae: 15.0943 - mse: 268.6393
Epoch 1

<Sequential name=sequential_13, built=True>

In [86]:
y_test

array([[ 7.276],
       [17.648],
       [22.248],
       [13.076],
       [ 9.922],
       [21.304],
       [ 7.796],
       [ 8.992],
       [25.58 ],
       [11.78 ],
       [14.51 ],
       [19.358],
       [20.408],
       [ 6.998],
       [16.928]])

In [85]:
model.model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step


array([[ 6.987361 ],
       [17.413343 ],
       [22.088194 ],
       [13.175597 ],
       [ 9.785656 ],
       [21.035675 ],
       [ 7.6449513],
       [ 9.164289 ],
       [25.547054 ],
       [11.592173 ],
       [14.459389 ],
       [19.395784 ],
       [20.28242  ],
       [ 7.2214203],
       [16.928331 ]], dtype=float32)

In [73]:
y_test

array([[ 7.276],
       [17.648],
       [22.248],
       [13.076],
       [ 9.922],
       [21.304],
       [ 7.796],
       [ 8.992],
       [25.58 ],
       [11.78 ],
       [14.51 ],
       [19.358],
       [20.408],
       [ 6.998],
       [16.928]])

In [74]:
loss, mse, mae = model.evaluateNN(X_test=np.array(X_test_scaled),y_test=y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step - loss: 255.6955 - mae: 14.8915 - mse: 255.6955


In [75]:
model.evaluateNN(X_test_scaled,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - loss: 266.0139 - mae: 15.3064 - mse: 266.0139


(266.0138854980469, 266.0138854980469, 15.306365966796875)

In [46]:
loss

163352.140625

In [47]:
mse

163352.140625

In [48]:
mae

360.4127502441406

In [80]:
X_test_scaled

array([[0.11111111, 0.16666667, 0.85714286],
       [0.66666667, 0.19047619, 0.        ],
       [0.88888889, 0.38095238, 0.28571429],
       [0.33333333, 0.9047619 , 0.5       ],
       [0.22222222, 0.42857143, 0.85714286],
       [0.88888889, 0.        , 0.78571429],
       [0.11111111, 0.4047619 , 0.5       ],
       [0.11111111, 0.95238095, 1.        ],
       [1.        , 0.88095238, 0.5       ],
       [0.33333333, 0.33333333, 0.35714286],
       [0.44444444, 0.61904762, 0.92857143],
       [0.66666667, 0.9047619 , 0.78571429],
       [0.77777778, 0.47619048, 0.92857143],
       [0.        , 1.        , 0.64285714],
       [0.55555556, 0.76190476, 1.        ]])

In [90]:
y_pred = model.model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step


In [89]:
y_test

array([[ 7.276],
       [17.648],
       [22.248],
       [13.076],
       [ 9.922],
       [21.304],
       [ 7.796],
       [ 8.992],
       [25.58 ],
       [11.78 ],
       [14.51 ],
       [19.358],
       [20.408],
       [ 6.998],
       [16.928]])

## Metric Calculation

In [92]:
from sklearn.metrics import mean_absolute_percentage_error as mape

In [93]:
mape(y_test,y_pred)

0.012894011931340793